### ISSUE TITLE
Receiving error using helpers.extension().loadRequest()

### ISSUE THREAD

**Issue by bdeanindy** [ringcentral/ringcentral-js-helpers#3]
While using the Extension helpers lib to retrieve all extensions within an account, I'm receiving the following error:

[TypeError: path.indexOf is not a function]

Here is the code I'm using:

```
// Already have setup the SDK and Platform successfully...

  platform
    .get(Extension.loadRequest())
    .then(function(extensions) {
      console.log(extensions);
    })  
    .catch(function(e) {
      console.error(e);
    }); 
```

When I replace `loadRequest()` with `createUrl()` everything works as expected.

**Comment by kirill-konshin** [comment]
You should use not `get()` method but `send()` method.

**Comment by bdeanindy** [comment]
You will want to update the documentation (in the ringcentral-js repository) then because it says I can use get() as the shorthand.

https://github.com/ringcentral/ringcentral-js/blob/master/README.md

It contains this:

// Shorthand methods

rcsdk.platform().get('/account/~/extension/~', {...query}).then(...);
rcsdk.platform().post('/account/~/extension/~', {...body}, {...query}).then(...);
rcsdk.platform().put('/account/~/extension/~', {...body}, {...query}).then(...);
rcsdk.platform().delete('/account/~/extension/~', {...query}).then(function(...);

**Comment by kirill-konshin** [comment]
Documentation of Helpers says:

``` js
platform.send(Call.loadRequest(null, {
```

`loadRequest` and other `*Request` methods are not intended to be used with shorthands.

**Comment by bdeanindy** [comment]
That wasn't readily apparent sir and I thought I could use them interchangeably.

Thanks for the pointer @kirill-konshin :+1:

**Comment by kirill-konshin** [comment]
The signature of shorthand methods is totally different from `send()` method.

**Comment by bdeanindy** [comment]
Thanks, I didn't know to look at the send(), doing that now. :)

**Comment by bdeanindy** [comment]
When I use the send() method, I keep getting this error:

[TypeError: Cannot assign to read only property 'url' of /account/~/extension]

**Comment by bdeanindy** [comment]
This seems to work, so I'm going to use it:

```
 54   platform
 55     .get(Extension.createUrl(), {
 56       query: {
 57         page: 1,
 58         perPage: 1000
 59       }
 60     })
```

**Comment by kirill-konshin** [comment]
``` js
   platform
     .get(Extension.createUrl(), {
         page: 1,
         perPage: 1000
     })
```

Without query in the hash. Query is the second parameter.

**Comment by bdeanindy** [comment]
BAH! Sorry, forgot to pull that out from when I was using the .get() shorthand method. Thanks. :100:
